Repository insightsengineering/teal, pull requests merged in 2023-11, with the labels that each got.

#957 Introduce the new DDL
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/dummy_functions.R
  R/init.R
  R/landing_popup_module.R
  R/module_nested_tabs.R
  R/module_snapshot_manager.R
  R/module_tabs_with_filters.R
  R/module_teal.R
  R/module_teal_with_splash.R
  R/modules.R
  R/teal_data_module.R
  R/utils.R
  _pkgdown.yml
  man/check_filter_datanames.Rd
  man/check_modules_datanames.Rd
  man/init.Rd
  man/landing_popup_module.Rd
  man/module_teal.Rd
  man/snapshot_manager_module.Rd
  man/srv_teal_with_splash.Rd
  man/teal_data_module.Rd
  man/ui_teal_with_splash.Rd
  tests/testthat/test-init.R
  tests/testthat/test-module_nested_tabs.R
  tests/testthat/test-module_teal.R
  tests/testthat/test-module_teal_with_splash.R
  tests/testthat/test-rcode_utils.R
  tests/testthat/test-teal_data_module.R
  vignettes/adding-support-for-reporting.Rmd
  vignettes/data-as-shiny-module.Rmd
Labels: core

#958 Make `JoinKeys` related changes due to refactor
  DESCRIPTION
  NAMESPACE
  R/module_filter_manager.R
  R/module_nested_tabs.R
  R/module_tabs_with_filters.R
  R/module_teal.R
  R/module_teal_with_splash.R
  R/modules.R
  R/modules_debugging.R
  R/tdata.R
  R/teal_slices.R
  R/utils.R
  _pkgdown.yml
  man/dot-datasets_to_data.Rd
  man/filter_calls_module.Rd
  man/get_join_keys.Rd
  man/join_keys.tdata.Rd
  man/module.Rd
  man/module_filter_manager_modal.Rd
  man/module_nested_tabs.Rd
  man/module_tabs_with_filters.Rd
  man/module_teal.Rd
  man/modules.Rd
  man/resolve_modules_datanames.Rd
  man/tdata.Rd
  man/teal_slices.Rd
  tests/testthat/test-module_nested_tabs.R
  tests/testthat/test-tdata.R
  vignettes/creating-custom-modules.Rmd
  vignettes/filter-panel.Rmd
  vignettes/teal-bs-themes.Rmd
  vignettes/teal.Rmd
Labels: core, refactor

#962 Extend `validate_has_data` to accept vector input
  NEWS.md
  R/validations.R
  tests/testthat/test-validate_has_data.R
Labels: bug, core

#924 904 teal_data in teal_module
  NAMESPACE
  NEWS.md
  R/dummy_functions.R
  R/init.R
  R/module_nested_tabs.R
  R/module_teal_with_splash.R
  R/modules.R
  R/tdata.R
  _pkgdown.yml
  man/dot-datasets_to_data.Rd
  man/example_module.Rd
  man/init.Rd
  man/module.Rd
  man/modules.Rd
  man/tdata.Rd
  man/tdata_deprecation.Rd
  tests/testthat/test-module_nested_tabs.R
  tests/testthat/test-tdata.R
Labels: core

#964 471 remove `CodeClass` from `FilteredData`
  DESCRIPTION
  NEWS.md
  R/get_rcode_utils.R
  R/init.R
  R/module_nested_tabs.R
  R/module_teal.R
  R/module_teal_with_splash.R
  R/utils.R
  man/get_datasets_code.Rd
  man/init.Rd
  man/teal_data_to_filtered_data.Rd
  tests/testthat/test-module_nested_tabs.R
  tests/testthat/test-module_tabs_with_filters.R
  tests/testthat/test-module_teal_with_splash.R
Labels: core

#970 update documentation for `teal_slices`
  R/teal_slices.R
  man/teal_slices.Rd
  vignettes/filter-panel.Rmd
Labels: core

#976 `get_code` to return concatenated code string
  vignettes/adding-support-for-reporting.Rmd
Labels: core

#978 vignette themes
  _pkgdown.yml
  vignettes/bootstrap-themes-in-teal.Rmd
Labels: core

#991 update example module
  R/dummy_functions.R
Labels: core

#990 vignette data
  .gitignore
  _pkgdown.yml
  vignettes/including-adam-data-in-teal.Rmd
  vignettes/including-data-in-teal-applications.Rmd
  vignettes/including-general-data-in-teal.Rmd
  vignettes/including-mae-data-in-teal.Rmd
  vignettes/preprocessing-data.Rmd
Labels: core

#980 vignette custom modules
  vignettes/creating-custom-modules.Rmd
Labels: core

#993 update example modules in vignettes
  vignettes/adding-support-for-reporting.Rmd
  vignettes/creating-custom-modules.Rmd
  vignettes/data-as-shiny-module.Rmd
Labels: core
