Repository insightsengineering/teal, pull requests merged in 2023-12, with the labels that each got.

#983 Adds `within` and `eval_code` to `teal_data_module`
  DESCRIPTION
  NAMESPACE
  R/teal_data_module-eval_code.R
  R/teal_data_module.R
  R/zzz.R
  _pkgdown.yml
  man/eval_code.Rd
  man/teal_data_module.Rd
  man/within.teal_data_module.Rd
  tests/testthat/test-module_nested_tabs.R
  tests/testthat/test-module_teal_with_splash.R
  tests/testthat/test-teal_data_module-eval_code.R
  vignettes/data-as-shiny-module.Rmd
Labels: enhancement, core

#1003 1000 fix empty selection in restore
  R/teal_slices-store.R
  tests/testthat/test-teal_slices-store.R
Labels: core

#1006 fix resolve_delayed
  .pre-commit-config.yaml
  DESCRIPTION
  NAMESPACE
  R/module_nested_tabs.R
  R/teal.R
  README.md
  staged_dependencies.yaml
  tests/testthat/test-module_nested_tabs.R
  tests/testthat/test-module_tabs_with_filters.R
  vignettes/blueprint/intro.Rmd
  vignettes/blueprint/product_map.Rmd
  vignettes/creating-custom-modules.Rmd
  vignettes/getting-started-with-teal.Rmd
Labels: core

#1002 996 collate documentation
  DESCRIPTION
  NAMESPACE
  R/teal_data_module-eval_code.R
  R/teal_data_module-within.R
  R/teal_data_module.R
  man/eval_code.Rd
  man/teal_data_module.Rd
  man/within.teal_data_module.Rd
Labels: core

#1012 985 get_code_dependency check_names=FALSE
  R/get_rcode_utils.R
Labels: core

#1004 999 set default datanames to ls(data@env)
  R/init.R
  R/module_teal.R
  R/module_teal_with_splash.R
  R/tdata.R
  R/utils.R
  man/init.Rd
  man/teal_data_datanames.Rd
  man/teal_data_to_filtered_data.Rd
  tests/testthat/test-init.R
  tests/testthat/test-module_teal_with_splash.R
  tests/testthat/test-tdata.R
  tests/testthat/test-utils.R
Labels: core

#1014 999 change names(teal_data) to ls(get_env(teal_data))
  R/utils.R
  tests/testthat/test-utils.R
Labels: core

#1020 Modifies tests as filter result uses a parent-child relationship by default
  tests/testthat/test-module_nested_tabs.R
Labels: bug, core
