Repository insightsengineering/teal, pull requests merged in 2023-07, with the labels that each got.

#858 Decouple scda
  DESCRIPTION
  NEWS.md
  R/dummy_functions.R
  R/init.R
  R/module_nested_tabs.R
  R/module_tabs_with_filters.R
  R/module_teal.R
  R/modules_debugging.R
  R/validations.R
  README.md
  man/example_cdisc_data.Rd
  man/example_datasets.Rd
  man/example_filter.Rd
  man/example_modules.Rd
  man/filter_calls_module.Rd
  man/init.Rd
  man/ui_nested_tabs.Rd
  man/ui_tabs_with_filters.Rd
  man/ui_teal.Rd
  man/validate_has_data.Rd
  man/validate_has_elements.Rd
  man/validate_has_variable.Rd
  man/validate_in.Rd
  man/validate_n_levels.Rd
  man/validate_no_intersection.Rd
  man/validate_one_row_per_id.Rd
  staged_dependencies.yaml
  tests/testthat/test-init.R
  vignettes/including-adam-data-in-teal.Rmd
  vignettes/preprocessing-data.Rmd
Labels: core

#849 extend default report previewer
  R/module_teal.R
  R/reporter_previewer_module.R
  man/reporter_previewer_module.Rd
Labels: core

#861 Update vignettes
  NAMESPACE
  R/example_module.R
  R/module_nested_tabs.R
  R/modules.R
  inst/js/sidebar.js
  man/example_module.Rd
  man/is_arg_used.Rd
  man/ui_nested_tabs.Rd
  vignettes/filter-panel.Rmd
  vignettes/images/filters_mapping.jpeg
  vignettes/images/teal.jpg
  vignettes/teal.Rmd
Labels: core

#863 355 rename module_add to allow_add
  R/teal_slices.R
  man/teal_slices.Rd
Labels: core

#865 Move TealReportCard to teal
  DESCRIPTION
  NAMESPACE
  R/teal_reporter.R
  R/zzz.R
  _pkgdown.yml
  inst/WORDLIST
  man/TealReportCard.Rd
  man/TealSlicesBlock.Rd
  tests/testthat/test-teal_reporter.R
  vignettes/adding-support-for-reporting.Rmd
Labels: core

#859 298 reset button
  DESCRIPTION
  NEWS.md
  R/module_filter_manager.R
  R/module_nested_tabs.R
  R/module_snapshot_manager.R
  R/module_tabs_with_filters.R
  R/module_teal.R
  R/teal_reporter.R
  R/teal_slices.R
  R/zzz.R
  inst/css/sidebar.css
  inst/js/sidebar.js
  man/TealSlicesBlock.Rd
  man/disassemble_slices.Rd
  man/filter_manager_module_srv.Rd
  man/matrix_to_mapping.Rd
  man/module_filter_manager.Rd
  man/module_filter_manager_modal.Rd
  man/reassemble_slices.Rd
  man/snapshot_manager_module.Rd
  man/teal_slices.Rd
  man/ui_nested_tabs.Rd
  man/unfold_mapping.Rd
  tests/testthat/test-filter_manager.R
  tests/testthat/test-init.R
  tests/testthat/test-module_tabs_with_filters.R
  tests/testthat/test-modules.R
  tests/testthat/test-snapshot_manager.R
  tests/testthat/test-teal_slices.R
Labels: core

#853 typo in creating-custom-modules.Rmd
  vignettes/creating-custom-modules.Rmd
Labels: documentation, core

#868 382 rename internal functions
  NAMESPACE
  R/init.R
  R/module_snapshot_manager.R
  R/teal_slices.R
  R/zzz.R
  man/disassemble_slices.Rd
  man/reassemble_slices.Rd
  man/teal_slices.Rd
  tests/testthat/test-snapshot_manager.R
Labels: core

#872 870 some bugs@main
  DESCRIPTION
  R/dummy_functions.R
  R/example_module.R
  R/module_filter_manager.R
  R/module_nested_tabs.R
  R/module_snapshot_manager.R
  R/module_tabs_with_filters.R
  R/module_teal.R
  man/example_datasets.Rd
  man/example_filter.Rd
  man/example_module.Rd
  man/example_modules.Rd
  man/module_nested_tabs.Rd
  man/module_tabs_with_filters.Rd
  man/module_teal.Rd
  man/srv_nested_tabs.Rd
  man/srv_tabs_with_filters.Rd
  man/srv_teal.Rd
  man/ui_tabs_with_filters.Rd
Labels: bug, help wanted, core

#869 818 documentation cleanup
  vignettes/adding-support-for-reporting.Rmd
Labels: core
