Repository insightsengineering/teal, pull requests merged in 2024-11, with the labels that each got.

#1393 Accept functions
  DESCRIPTION
  R/module_data_summary.R
  R/module_init_data.R
  R/utils.R
  man/dot-smart_rbind.Rd
  man/module_data_summary.Rd
  tests/testthat/test-module_teal.R
  tests/testthat/test-rcode_utils.R
  tests/testthat/test-shinytest2-data_summary.R
  tests/testthat/test-utils.R
Labels: core

#1401 Modify the print for modules to contain more information
  .pre-commit-config.yaml
  DESCRIPTION
  R/modules.R
  R/utils.R
  inst/WORDLIST
  man/teal_modules.Rd
  tests/testthat/test-modules.R
Labels: enhancement, core

#1402 `teal.data::datanames()` is deprecated in favor of dot-prefix and `ls()`
  .pre-commit-config.yaml
  DESCRIPTION
  R/dummy_functions.R
  R/init.R
  R/module_data_summary.R
  R/module_init_data.R
  R/module_nested_tabs.R
  R/module_teal.R
  R/module_teal_data.R
  R/teal_data_module.R
  R/teal_data_utils.R
  R/utils.R
  man/dot-get_hashes_code.Rd
  man/teal_data_module.Rd
  man/teal_data_to_filtered_data.Rd
  man/teal_data_utilities.Rd
  tests/testthat/helper-shinytest2.R
  tests/testthat/test-module_teal.R
  tests/testthat/test-shinytest2-data_summary.R
  tests/testthat/test-shinytest2-teal_data_module.R
  tests/testthat/test-teal_data_module-eval_code.R
  tests/testthat/test-utils.R
  vignettes/adding-support-for-reporting.Rmd
  vignettes/creating-custom-modules.Rmd
  vignettes/data-as-shiny-module.Rmd
  vignettes/data-transform-as-shiny-module.Rmd
  vignettes/including-data-in-teal-applications.Rmd
Labels: core

#1396 Adjust `teal` after introduction of `[.qenv` in `teal.code` and after changes of `@code`, `@warnings`, `@messages` and `@id` slots
  R/module_nested_tabs.R
  R/teal_data_utils.R
  R/zzz.R
  man/teal_data_utilities.Rd
  tests/testthat/test-module_teal.R
  tests/testthat/test-shinytest2-show-rcode.R
Labels: core

#1405 Update versions of `teal.data` and `teal.code`
  DESCRIPTION
Labels: core

#1406 Remove TealData checks
  R/init.R
  R/modules.R
  man/teal_data_module.Rd
  tests/testthat/test-modules.R
Labels: core

#1416 Adds warning on reserved datanames ("all")
  NEWS.md
  R/utils.R
  man/check_modules_datanames.Rd
  man/pluralize.Rd
  tests/testthat/test-init.R
  tests/testthat/test-module_teal.R
Labels: core

#1414 Update teal.slice version
  DESCRIPTION
Labels: core

#1419 Fixes `setup-r-dependencies` by adding `rtables.officer`
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/scheduled.yaml
Labels: bug, core

#1418 Update decorators vignette for multiple decorators
  vignettes/decorate-module-output.Rmd
Labels: core

#1423 Fix examples on decorator vignette
  vignettes/decorate-module-output.Rmd
Labels: core

#1410 Resolve todos
  R/module_data_summary.R
  R/module_filter_manager.R
  R/module_nested_tabs.R
  R/module_snapshot_manager.R
  R/module_teal.R
  R/module_transform_data.R
  tests/testthat/test-rcode_utils.R
Labels: core

#1357 Adds decorate functionality to module output
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/scheduled.yaml
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/dummy_functions.R
  R/init.R
  R/module_data_summary.R
  R/module_nested_tabs.R
  R/module_teal.R
  R/module_teal_data.R
  R/module_transform_data.R
  R/modules.R
  R/teal_data_module-within.R
  R/teal_data_module.R
  R/teal_transform_module.R
  _pkgdown.yml
  inst/WORDLIST
  man/example_module.Rd
  man/extract_transformators.Rd
  man/extract_transformers.Rd
  man/make_teal_transform_server.Rd
  man/module_teal_data.Rd
  man/module_transform_data.Rd
  man/teal_data_module.Rd
  man/teal_modules.Rd
  man/teal_transform_module.Rd
  tests/testthat/test-init.R
  tests/testthat/test-module_teal.R
  tests/testthat/test-modules.R
  tests/testthat/test-shinytest2-decorators.R
  tests/testthat/test-shinytest2-show-rcode.R
  tests/testthat/test-teal_data_module.R
  tests/testthat/test-teal_transform_module.R
  vignettes/data-transform-as-shiny-module.Rmd
  vignettes/decorate-module-output.Rmd
Labels: core
