Repository insightsengineering/teal, pull requests merged in 2024-01, with the labels that each got.

#1018 Add a helper function to add app title with a favicon
  R/init.R
  R/utils.R
  _pkgdown.yml
  inst/WORDLIST
  man/build_app_title.Rd
  man/init.Rd
  man/module_teal.Rd
  man/srv_teal_with_splash.Rd
  man/ui_teal_with_splash.Rd
  man/validate_app_title_tag.Rd
  tests/testthat/test-utils.R
Labels: enhancement, core

#1022 Export the user facing function and update changelog
  NAMESPACE
  NEWS.md
  R/utils.R
Labels: core

#1030 include parent datasets to the modules
  R/module_nested_tabs.R
  R/module_tabs_with_filters.R
  R/utils.R
Labels: core

#1008 align args asserts; align args defaults; logger in test
  R/init.R
  R/module_teal.R
  R/module_teal_with_splash.R
  R/modules.R
  R/utils.R
  R/validate_inputs.R
  man/build_app_title.Rd
  man/create_app_id.Rd
  man/init.Rd
  man/module_teal.Rd
  man/ui_teal_with_splash.Rd
  tests/testthat/setup-logger.R
  tests/testthat/test-init.R
  tests/testthat/test-module_teal_with_splash.R
  tests/testthat/test-modules.R
  tests/testthat/test-validate_inputs.R
Labels: core

#1051 1031 drop list support
  NEWS.md
  R/init.R
  R/teal_slices.R
  R/utils.R
  man/init.Rd
  man/srv_teal_with_splash.Rd
  man/teal_slices.Rd
  man/ui_teal_with_splash.Rd
  tests/testthat/test-init.R
Labels: core

#1038 1009 fix skipped tests
  tests/testthat/test-module_nested_tabs.R
  tests/testthat/test-tdata.R
Labels: core

#1037 492 user feedback on documentation
  R/dummy_functions.R
  R/teal_data_module-within.R
  man/teal_data_module.Rd
  vignettes/adding-support-for-reporting.Rmd
  vignettes/creating-custom-modules.Rmd
  vignettes/data-as-shiny-module.Rmd
  vignettes/images/custom_app.png
  vignettes/images/show_code_prepro_missing.png
  vignettes/images/show_code_prepro_present.png
  vignettes/including-data-in-teal-applications.Rmd
Labels: core

#1054 942 rename toString to format for modules methods
  NAMESPACE
  R/modules.R
  man/module.Rd
  man/modules.Rd
  tests/testthat/test-modules.R
Labels: core

#1061 492 user feedback revisited
  vignettes/including-data-in-teal-applications.Rmd
Labels: core

#1065 430 use `expect_no_error` in tests instead of `expect_error(, NA)`
  DESCRIPTION
  tests/testthat/test-module_nested_tabs.R
  tests/testthat/test-report_previewer_module.R
  tests/testthat/test-tdata.R
  tests/testthat/test-teal_reporter.R
  tests/testthat/test-utils.R
Labels: core

#1064 add css to blur out background when using landing popup module
  inst/css/custom.css
Labels: core

#1057 Fix getting-started-with-teal
  inst/design/filters-mapping.drawio
  inst/design/teal-app-components-hover.drawio
  inst/design/teal-app-components.drawio
  vignettes/blueprint/actors.Rmd
  vignettes/blueprint/in_app_data.Rmd
  vignettes/blueprint/intro.Rmd
  vignettes/creating-custom-modules.Rmd
  vignettes/filter-panel.Rmd
  vignettes/getting-started-with-teal.Rmd
  vignettes/images/example_app.png
  vignettes/images/filters-mapping.svg
  vignettes/images/filters_mapping.jpg
  vignettes/images/teal-app-components-hover.svg
  vignettes/images/teal-app-components.svg
Labels: core

#1070 Pass the check status to the main teal_data function call
  DESCRIPTION
  R/module_nested_tabs.R
  R/utils.R
Labels: bug, core

#1026 Adding internal examples
  R/include_css_js.R
  R/module_filter_manager.R
  R/module_nested_tabs.R
  R/module_tabs_with_filters.R
  R/module_teal.R
  R/modules.R
  R/modules_debugging.R
  R/teal_slices-store.R
  man/filter_calls_module.Rd
  man/include_teal_css_js.Rd
  man/module_filter_manager_modal.Rd
  man/module_nested_tabs.Rd
  man/module_tabs_with_filters.Rd
  man/module_teal.Rd
  man/modules_depth.Rd
  man/slices_restore.Rd
  man/slices_store.Rd
Labels: core

#1053 1032 fix ellipsis documentation for `teal::modules()`
  NAMESPACE
  R/modules.R
  man/module.Rd
  man/modules.Rd
  tests/testthat/test-modules.R
Labels: core
