Repository insightsengineering/teal, pull requests merged in 2025-02, with the labels that each got.

#1477 vbump teal.widgets
  DESCRIPTION
Labels: core

#1472 Add roxy.shinylive
  .pre-commit-config.yaml
  DESCRIPTION
  R/dummy_functions.R
  R/init.R
  R/module_session_info.R
  R/modules.R
  R/teal_modifiers.R
  R/teal_slices.R
  R/teal_transform_module.R
  R/validate_inputs.R
  R/validations.R
  inst/WORDLIST
  man/add_landing_modal.Rd
  man/example_module.Rd
  man/init.Rd
  man/make_teal_transform_server.Rd
  man/module_session_info.Rd
  man/teal_modifiers.Rd
  man/teal_modules.Rd
  man/teal_slices.Rd
  man/teal_transform_module.Rd
  man/validate_has_data.Rd
  man/validate_has_elements.Rd
  man/validate_has_variable.Rd
  man/validate_in.Rd
  man/validate_inputs.Rd
  man/validate_n_levels.Rd
  man/validate_no_intersection.Rd
  man/validate_one_row_per_id.Rd
  staged_dependencies.yaml
  vignettes/adding-support-for-reporting.Rmd
  vignettes/bootstrap-themes-in-teal.Rmd
  vignettes/creating-custom-modules.Rmd
  vignettes/data-as-shiny-module.Rmd
  vignettes/data-transform-as-shiny-module.Rmd
  vignettes/filter-panel.Rmd
Labels: documentation, enhancement, core

#1470 Review decorator vignette
  _pkgdown.yml
  vignettes/customizing-module-output.Rmd
  vignettes/decorate-module-output.Rmd
Labels: core

#1467 Vignette: shiny as a module
  R/module_session_info.R
  R/module_teal.R
  _pkgdown.yml
  man/module_session_info.Rd
  man/module_teal.Rd
  vignettes/getting-started-with-teal.Rmd
  vignettes/teal-as-a-module.Rmd
Labels: core

#1479 vbump teal.slice
  DESCRIPTION
Labels: core

#1482 Remove unused
  DESCRIPTION
  R/get_rcode_utils.R
  man/get_rcode_libraries.Rd
  tests/testthat/test-rcode_utils.R
Labels: core

#1478 Transformer called too early
  R/module_nested_tabs.R
  R/module_transform_data.R
  man/dot-call_once_when.Rd
Labels: core

#1476 improve vignettes for transformers and decorators
  R/dummy_functions.R
  R/modules.R
  R/teal_transform_module.R
  _pkgdown.yml
  inst/WORDLIST
  inst/design/teal-app-components-hover.drawio
  man/example_module.Rd
  man/teal_modules.Rd
  man/teal_transform_module.Rd
  vignettes/adding-support-for-reporting.Rmd
  vignettes/blueprint/intro.Rmd
  vignettes/blueprint/module_encapsulation.Rmd
  vignettes/bootstrap-themes-in-teal.Rmd
  vignettes/creating-custom-modules.Rmd
  vignettes/customizing-module-output.Rmd
  vignettes/data-as-shiny-module.Rmd
  vignettes/data-transform-as-shiny-module.Rmd
  vignettes/getting-started-with-teal.Rmd
  vignettes/teal-as-a-shiny-module.Rmd
  vignettes/teal-options.Rmd
Labels: core

#1488 fix: add missing staged.dependencies entry
  staged_dependencies.yaml
Labels: core

#1487 Raise a shiny silent error when data is NULL
  R/module_transform_data.R
Labels: core

#1489 Improve the definition of "transform" in the vignettes
  R/dummy_functions.R
  R/modules.R
  R/teal_transform_module.R
  _pkgdown.yml
  inst/design/teal-transform-module-decorators.drawio
  inst/design/teal-transform-module-transformators.drawio
  man/example_module.Rd
  man/module_transform_data.Rd
  man/teal_modules.Rd
  man/teal_transform_module.Rd
  vignettes/images/teal-transform-module-decorators.svg
  vignettes/images/teal-transform-module-transformators.svg
  vignettes/transform-input-data.Rmd
  vignettes/transform-module-output.Rmd
Labels: documentation, core

#1495 1494 fix note
  R/dummy_functions.R
Labels: core

#1497 Merge main to test@bslib@main
  DESCRIPTION
  NEWS.md
  R/dummy_functions.R
  R/init.R
  R/landing_popup_module.R
  R/module_teal_with_splash.R
  R/show_rcode_modal.R
  R/tdata.R
  R/utils.R
  man/init.Rd
  man/module_teal_with_splash.Rd
  tests/testthat.R
Labels: core
